### PR TITLE
Replace HostTransfer backend with NCCL

### PR DESCRIPTION
**Pull request by ndryden**
This essentially does a find-replace of the `HostTransfer` backend with the `NCCL` backend, since Aluminum's NCCL backend supports point-to-point communication. No filenames/etc. have been changed, so some things still refer to "mpi_cuda" and so on (but since that name was _already_ outdated, I'm not too worried).

This also bumps the minimum Aluminum version to 1.0.0 and the needed C++ and CUDA standards (to be able to compile the Aluminum headers).

Passed simple tests with `distconv_benchmark`.

### CODE REVIEW

**Comment by bvanessen** [comment]
@benson31 To be clear this replaces the HT backend, so it is no longer an option, is that correct?

**Comment by ndryden** [comment]
@bvanessen (I am not Tom, but I can answer this.)

It completely replaces it and the HT backend is no longer an option. This was never configurable because it is hardcoded throughout the code.

**Review by timmoon10 — APPROVED** [review]
LGTM

**Review by bvanessen — CHANGES_REQUESTED** [review]
Is this still relevant.  Should the PR be closed?  Don't we still want the HT backend?

**Comment by benson31** [comment]
Replaced by #68.

**Pull request closed without merging**
